### ISSUE TITLE
Mailboxes don't know what they're made out of

### ISSUE THREAD

**Issue by LemmaEOF** [Patbox/PolyDecorations#11]
Mailboxes seem to change their textures every time I log onto a server with polydeco (0.4.0+1.21) on it. I have polydeco on my client as well, but that doesn't feel like it should affect anything. I don't run the server but if needed I can grab client/server mod lists.

![2024-06-25_13 15 59](https://github.com/Patbox/PolyDecorations/assets/6722691/637a4aeb-d892-4e6e-bd7a-4c51ee7a527f)
![2024-06-25_13 16 02](https://github.com/Patbox/PolyDecorations/assets/6722691/03a8e830-7093-4d31-8d91-65e7d9ae912d)

**Comment by Patbox** [comment]
You are running with it on the client? (aka the "regular" modded setup)

**Comment by LemmaEOF** [comment]
yeah, it's on client - I didn't expect recipes to show up in EMI if I didn't
