### ISSUE TITLE
required on client side?

### ISSUE THREAD

**Issue by Legendmanj** [Patbox/PolyDecorations#12]
is this mod required on the client side in order to see the modules/furnitures? or only to be used on the server alone and vanilla clients will still be able to see and intract with them without needing to use any resoucepack or anyhting

**Comment by Patbox** [comment]
It is only required to be installed on the server with server resource pack hosting enabled (see https://polymer.pb4.eu/latest/user/resource-pack-hosting/). But it will work in singleplayer / when installed in both side configuration without extra setup
