### ISSUE TITLE
the mod does not load the furnitures

### ISSUE THREAD

**Issue by Legendmanj** [Patbox/PolyDecorations#13]
don't know why, but please assist me in fixing it, i have set up the polymer mod required and enabled the options for it in config to autohost, and it does seem to download the resoucepack on client but when searching for the items in creative the items doesn't show up at all.

Pretty good mod and that it is on server-side, would love it if it came to work 

thank you, would appreciate it if you assist me on fixing this asap

**Comment by Legendmanj** [comment]
MATE!! seems that i am suppose to run the command /polymer creative in order to access the furnitures, but does this mean that it isnt a mod for survival worlds? i would like to have it have a recipe in order to craft and use it in the world without any issues, please mind replying to my message 

thankyou  (;

**Comment by Patbox** [comment]
Everything should be craftable. You can use Polydex or vanilla recipe book (recipes should be unlocked by getting required planks)

**Comment by Legendmanj** [comment]
> Everything should be craftable. You can use Polydex or vanilla recipe book (recipes should be unlocked by getting required planks)

it can be seen on vanilla recipe book? it didnt seem like it as i went to creative to check and it wasnt present there tbh

**Comment by Legendmanj** [comment]
> Everything should be craftable. You can use Polydex or vanilla recipe book (recipes should be unlocked by getting required planks)

got my answer on discord, thank you for creating such a good mod lmao (;
