### ISSUE TITLE
Kicked from server when placing

### ISSUE THREAD

**Issue by andriibeshta** [Patbox/PolyDecorations#17]
Hello, I am having a problem. Mod is installed server-side and working correctly, but whenever I try to place tables next to each other (for them to connect) I get kicked off the server. When I log back in they're unified into a single table but its a bit of a hassle when decorating large spaces.

**Comment by Patbox** [comment]
Send client and server logs

**Comment by Patbox** [comment]
Can you replicate it with pure vanilla client?

**Comment by Patbox** [comment]
Also try updating polymer to latest 0.9.x version (1.21.1 is compatible with 1.21). If that doesn't help try removing connectivity mod on server

**Comment by andriibeshta** [comment]
Yep, connectivity it was. Works once removed. Any idea why they don't want to play with each other? Any way to fix this?

**Comment by Patbox** [comment]
I suggest just not using it, as it pretty much doesn't really effect things. You could maybe report that issue to them, but not sure if it will be fixed

**Comment by andriibeshta** [comment]
Got ya, thank you!
