### ISSUE TITLE
More info on what the mod can do

### ISSUE THREAD

**Issue by AlexanderwithaA** [Patbox/PolyDecorations#3]
Could more information be added on what features this mod has? I saw that the painting on modrinth had 4 shades of green which as far as I know isn’t possible and I later discovered that brushes could be used to make painting easier. Could more info be added on this sort of stuff?

**Comment by Patbox** [comment]
Yeah I should document it more. You can use coal and bone meal to change the shade

**Comment by AlexanderwithaA** [comment]
Awesome to know, suggestion though, maybe ink sacs instead of coal.

That does make me wonder, would you revamp the painting system? It’s a bit cumbersome. The use of a paint tray would be much more fun to use. Scroll to change paint, shift right click to open an inventory where you can put your dyes and ink/bonemeal, and shift left click to cycle the shade. Would be very cool.

**Comment by Patbox** [comment]
I can experiment with it a bit, but main limitation is keeping it fully functional with purely vanilla clients

**Comment by DearFox** [comment]
> Yeah I should document it more. You can use coal and bone meal to change the shade
I made this palette of all the colors that can be obtained in the mod, you can use it for documentation if you want.
![Colors_minecraftServerMod](https://github.com/Patbox/PolyDecorations/assets/59219907/d83dcad2-c421-4f55-bbac-bd2d07ead99e)
And a pixel palette, if suddenly you want to use it as a palette for drawing in some program.
![Colors_minecraftServerMod_original](https://github.com/Patbox/PolyDecorations/assets/59219907/c9d53895-35b0-4240-8abf-027f466e5e55)

I'm currently working on a convenient way to transfer finished pictures into this mod (for survival mode, of course).  But I need time to check this in the game and make a guide on how to do it.

**Comment by AlexanderwithaA** [comment]
I believe this to be finished since the painting stuff now has a tool tip
