### ISSUE TITLE
Suggestion, visuals

### ISSUE THREAD

**Issue by EfficientStinkbug** [Patbox/PolyDecorations#9]
Great mod! 
For the benches the crafting recipes output the wrong wood-type of the bench. (The name is correct but not the texture)

**Comment by Patbox** [comment]
Do you use Polymer Autohost for the pack? Or is it bundled with a modpack?

**Comment by EfficientStinkbug** [comment]
Not polymer autohost, but I use it with a ton of other mods. A figured something out: If I play on singleplayer it's completetly fine, it happens just when playing on my server. The mod versions are the same thought.
